### ISSUE TITLE
No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by lukyncze** [bitlabstudio/cmsplugin-image-gallery#16]
Hello, I wanted to install this plugin and this happens when I make migrations. Any ideas?

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\Final-project\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Final-project\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\Final-project\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Final-project\env\lib\site-packages\image_gallery\models.py", line 4, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by shuttle1987** [comment]
I'm guessing this is a version mismatch of some sort because in Django 2 you would use `from django.urls import reverse` instead of `from django.core.urlresolvers import reverse`.

**Comment by lukyncze** [comment]
Oh yeah, I had version Django 3. Thank you for replying.

**Comment by shuttle1987** [comment]
> Oh yeah, I had version Django 3. Thank you for replying.

If this didn't fix your issue I'd recommend updating the version of cmsplugin-image-gallery.

Perhaps the `install_requires` in this project's setup.py could be changed to indicate the incompatibility with old Django 1.x versions by requiring that Django is recent enough?

**Comment by lukyncze** [comment]
I had installed the newest version. 

I wanted any plugin that can be used with Django 3 and I got already one.
